import { ITheme } from "./style";

export const light: ITheme = {
    colors: {
        activeColor: "#000",
        gapColor: "#F7F7F7",
        linkDefaultColor: "#617168",
        linkActiveBgColor: "#DFE1E0",
        headerButtonColor: "#57625C",
        boxBgColor: "#FFFFFF",
        baseColor: "#000",
        backgroundColor: "#F7F7F7",
        labelColor: "#617168",
        long: "#157336",
        short: "#B4190D",
        tabColor: "#617168",
        tabSelectedColor: "#0A745A",
        tabSelectedBColor: "#fff",
        inputBgColor: "#DFE1E0",
        disabledButtonBgColor: "#F3F3F3",
        inputBtnBgColor: "#EEEFEF",
        modalTitle: "#000",
        subtitle: "#525150",
        filedColor: "#fff",
        modalBgColor: "#000",
        modalBorderColor: "#DFE1E0",
        activeBgColor: "#22352C",
        explain: "#57625C",
        borderColor: "#57625C",
        cancelBgColor: "#57625C",
        cancelColor: "#FFFFFF",
        confirmBgColor: "#C8CAC9",
        confirmColor: "#3E403F",
        borderColor2: "#DFE1E0",
        tabActiveColor: "#233918",
        stepColor: "#AFAFC4",
        stepActiveColor: "#F6F7F0",
        stepBorderColor: "#D7D7E2",
        emptyTextColor: "#525150",
        warnBgColor: "#121212",
        menuBgColor: "#121212",
        articleColor: "#FFFEFC",
        articleHrColor: "#0D0D0D",
    }
};
